"""
Fake model catalogue returned by GET /api/tags and GET /v1/models.
Models are realistic enough to pass casual inspection.
"""

from datetime import datetime, timezone

FAKE_MODELS = [
    {
        "name": "llama3.2:latest",
        "modified_at": "2024-10-15T12:00:00.000000Z",
        "size": 2019393189,
        "digest": "a80c4f17acd55265feec403c7aef86be0c25983ab279d83f3bcd3abbcb5b8b72",
        "details": {
            "format": "gguf",
            "family": "llama",
            "families": ["llama"],
            "parameter_size": "3.2B",
            "quantization_level": "Q4_K_M",
        },
    },
    {
        "name": "mistral:7b",
        "modified_at": "2024-09-20T08:30:00.000000Z",
        "size": 4108916857,
        "digest": "61e88e884507ba5e06c49b40e6226884b2a16e872382c2b44a42f2d119d804a5",
        "details": {
            "format": "gguf",
            "family": "llama",
            "families": ["llama"],
            "parameter_size": "7.2B",
            "quantization_level": "Q4_0",
        },
    },
    {
        "name": "codellama:13b",
        "modified_at": "2024-08-10T14:45:00.000000Z",
        "size": 7365960935,
        "digest": "9f438cb9cd581fc025612d27f7c1a6669ff83a8bb0ed86c94fcf4c5440555697",
        "details": {
            "format": "gguf",
            "family": "llama",
            "families": ["llama"],
            "parameter_size": "13B",
            "quantization_level": "Q4_K_M",
        },
    },
    {
        "name": "phi3:mini",
        "modified_at": "2024-07-25T10:00:00.000000Z",
        "size": 2176178913,
        "digest": "4f2222927938d0b89bcd3f79e2db9d64bb7849db30a8f0a907b61ac77a77af2d",
        "details": {
            "format": "gguf",
            "family": "phi3",
            "families": ["phi3"],
            "parameter_size": "3.8B",
            "quantization_level": "Q4_K_M",
        },
    },
    {
        "name": "gemma2:2b",
        "modified_at": "2024-09-01T09:15:00.000000Z",
        "size": 1629518495,
        "digest": "8ccf136fdd5298f3d8f8f674c61c44df2e8d1b88c5cef66558a0012e3f1f60b2",
        "details": {
            "format": "gguf",
            "family": "gemma2",
            "families": ["gemma2"],
            "parameter_size": "2.6B",
            "quantization_level": "Q4_K_M",
        },
    },
    {
        "name": "qwen2.5:7b",
        "modified_at": "2024-10-01T11:00:00.000000Z",
        "size": 4683075584,
        "digest": "845dbda0ea48ef83c916b7d0f02c9e5ebb4e10cfce4ae90d49dc47d1f62d9573",
        "details": {
            "format": "gguf",
            "family": "qwen2",
            "families": ["qwen2"],
            "parameter_size": "7.6B",
            "quantization_level": "Q4_K_M",
        },
    },
    {
        "name": "deepseek-r1:8b",
        "modified_at": "2025-01-20T16:30:00.000000Z",
        "size": 4920166560,
        "digest": "28f8fd6cdc6740dd3a79f2c40e6c5f5f1b8b6e8c6e5d8d6a5c4b3a2918e7d6c5",
        "details": {
            "format": "gguf",
            "family": "llama",
            "families": ["llama"],
            "parameter_size": "8.0B",
            "quantization_level": "Q4_K_M",
        },
    },
]

# Map model name → details for /api/show lookups
MODEL_DETAILS = {m["name"]: m for m in FAKE_MODELS}
# Also index by base name (without tag)
for _m in FAKE_MODELS:
    _base = _m["name"].split(":")[0]
    MODEL_DETAILS.setdefault(_base, _m)


def get_tags_response() -> dict:
    return {"models": FAKE_MODELS}


def get_show_response(name: str) -> dict:
    model = MODEL_DETAILS.get(name) or FAKE_MODELS[0]
    return {
        "license": "Community License Agreement",
        "modelfile": (
            f"# Modelfile generated by 'ollama show'\n"
            f"FROM {model['name']}\n"
            f"SYSTEM You are a helpful AI assistant.\n"
        ),
        "parameters": "num_ctx 4096\nnum_gpu 1",
        "template": (
            "{{ if .System }}<|system|>\n{{ .System }}<|end|>\n{{ end }}"
            "{{ if .Prompt }}<|user|>\n{{ .Prompt }}<|end|>\n{{ end }}"
            "<|assistant|>\n{{ .Response }}<|end|>\n"
        ),
        "details": model["details"],
    }


def get_ps_response() -> dict:
    return {
        "models": [
            {
                "name": FAKE_MODELS[0]["name"],
                "model": FAKE_MODELS[0]["name"],
                "size": 2019393189,
                "digest": FAKE_MODELS[0]["digest"],
                "details": FAKE_MODELS[0]["details"],
                "expires_at": "2099-12-31T23:59:59Z",
                "size_vram": 2019393189,
            }
        ]
    }
